language: android
script: "./gradlew clean assembleDevelopmentHerokuDebug"
android:
  components:
  - build-tools-20.0.0
android_toolkit: 
deploy:
  provider: s3
  access_key_id: AKIAJ4AN2EBKO5SY5DCA
  secret_access_key:
    secure: ZtupPSzV0yig62s6Q/IVKT52XTGxAkRlAB0sZ8wT15WmKsiTRMhen0lKEDKk4VDRur2UgwdklMeVWw2a8ALvNmJ81+/K8TxuFrxppbB74ZgERxuP/Fabpn8jYx54ruS9c4SQFxDSv5w56xKNg1yEtRaE7oHXL0gVLpb70rw4r4Q=
  bucket: hamsterhelper
  skip_cleanup: true
  acl: !ruby/string:HighLine::String private
  local-dir: app/build/outputs/apk/app-developmentHeroku-debug.apk
  on:
    repo: forkch/hamsterhelper
